# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

require_relative 'OpenTokSDKVersion'

target 'cARt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cARt
  pod 'OpenTok', OpenTokSDKVersion

end
